name: Deploy action 
on:
  push:
    branches: [main, beta, alpha]

jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # need to checkout in order to run local action 
      - name: semantic-release setup
        uses: ./ 
      # You can use whatever method that you wish to run semantic-release. 
      # This action is my current go-to to run it. 
      - name: Deploy via semantic release 
        uses: cycjimmy/semantic-release-action@v2
        with: 
          # version numbers below can be in many forms: M, M.m, M.m.p
          semantic_version: 18
          extra_plugins: |
            @semantic-release/git@10
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PUSH_TOKEN }}